---
- name: running system_user tasks
  include_tasks: system_user.yml
  loop: "{{ system_user | dict2items }}"
  loop_control:
    label: "{{ system_user_item['key'] }}"
    loop_var: system_user_item
  when:
    - system_user is defined
