---
- name: running system_user_management tasks
  block:
    - name: creating user
      ansible.builtin.user:
        append: "{{ item['value']['append'] | default(omit) }}"
        authorization: "{{ item['value']['authorization'] | default(omit) }}"
        comment: "{{ item['value']['comment'] | default(omit) }}"
        create_home: "{{ item['value']['create_home'] | default(omit) }}"
        expires: "{{ item['value']['expires'] | default(omit) }}"
        generate_ssh_key: "{{ item['value']['generate_ssh_key'] | default(omit) }}"
        group: "{{ item['value']['group'] | default(omit) }}"
        groups: "{{ item['value']['groups'] | default(omit) }}"
        hidden: "{{ item['value']['hidden'] | default(omit) }}"
        home: "{{ item['value']['home'] | default(omit) }}"
        local: "{{ item['value']['local'] | default(omit) }}"
        login_class: "{{ item['value']['login_class'] | default(omit) }}"
        move_home: "{{ item['value']['move_home'] | default(omit) }}"
        name: "{{ item['value']['name'] }}"
        non_unique: "{{ item['value']['non_unique'] | default(omit) }}"
        password: "{{ item['value']['password'] | default(omit) }}"
        password_expire_max: "{{ item['value']['password_expire_max'] | default(omit) }}"
        password_expire_min: "{{ item['value']['password_expire_min'] | default(omit) }}"
        password_lock: "{{ item['value']['password_lock'] | default(omit) }}"
        profile: "{{ item['value']['profile'] | default(omit) }}"
        role: "{{ item['value']['role'] | default(omit) }}"
        seuser: "{{ item['value']['seuser'] | default(omit) }}"
        shell: "{{ item['value']['shell'] | default(omit) }}"
        skeleton: "{{ item['value']['skeleton'] | default(omit) }}"
        ssh_key_bits: "{{ item['value']['ssh_key_bits'] | default(omit) }}"
        ssh_key_comment: "{{ item['value']['ssh_key_comment'] | default(omit) }}"
        ssh_key_file: "{{ item['value']['ssh_key_file'] | default(omit) }}"
        ssh_key_passphrase: "{{ item['value']['ssh_key_passphrase'] | default(omit) }}"
        ssh_key_type: "{{ item['value']['ssh_key_type'] | default(omit) }}"
        state: present
        system: "{{ item['value']['system'] | default(omit) }}"
        uid: "{{ item['value']['uid'] | default(omit) }}"
        umask: "{{ item['value']['umask'] | default(omit) }}"
        update_password: "{{ item['value']['update_password'] | default(omit) }}"
      loop: "{{ system_user_management | dict2items }}"
      loop_control:
        label: "{{ item['key'] }}"
      when:
        - item['value']['name'] is defined
        - item['value']['state'] is defined and
          item['value']['state'] == "present" or
          item['value']['state'] is undefined

    - name: removing user
      ansible.builtin.user:
        force: "{{ item['value']['force'] | default(omit) }}"
        name: "{{ item['value']['name'] }}"
        remove: "{{ item['value']['remove'] | default(omit) }}"
        state: absent
      loop: "{{ system_user_management | dict2items }}"
      loop_control:
        label: "{{ item['key'] }}"
      when:
        - item['value']['name'] is defined
        - item['value']['state'] is defined
        - item['value']['state'] == "absent"
  when:
    - system_user_management is defined
